### ISSUE TITLE
Unable to find dataset folder

### ISSUE THREAD

**Issue by Momina12** [sidhiadkoli/lang-id#1]
I can't find the sa3505_data folder anywhere in your project. Can you please share it with me?
Thanks in advance

**Comment by asadullah797** [comment]
I am also searching for the sa3505_data dataset folder in this repo.
Can you please share with us.

**Comment by sidhiadkoli** [comment]
Thanks for your interest in this project. The datasets used are licensed, purchased for research purposes and thus cannot be shared. You will need to obtain them yourself. 
These were the datasets used:
- [Mandarin Chinese](https://catalog.ldc.upenn.edu/LDC96T16).
- [Arabic](https://catalog.ldc.upenn.edu/LDC2005S08).

The [English dataset](https://www.openslr.org/7/) is available publicly for non-commercial purpose.

While the above were the datasets used for this project, you can use anything that you have on hand. Once they are preprocessed to the correct format, the rest of the training scripts would be agnostic to the actual data.
